version: "3"

services:

    db:
        image: mdillon/postgis
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
    web:
        build: .
        restart: always
        depends_on:
          - db
        volumes:
            - /static:/var/www/spaceag/static
    nginx:
        restart: always
        build: ./configuration/development/nginx
        ports:
            - "80:8000"
        depends_on:
          - web
        volumes:
            - /static:/var/www/spaceag/static
